### ISSUE TITLE
BirdDog autotracking feature

### ISSUE THREAD

**Issue by Thijsvnl** [bitfocus/companion-module-birddog-ptz#132]
Hello everybody,
Since the introduction of CamControl 3 by BirdDog many their cameras support autotracking. Its an add-on that improves (quite well) the feeling that a real camerawomen/camaramen is behind the camera. 

It would be great if the related functions could be implemented in the Companion Module. Have a look at some screenshots. 

![Schermafbeelding 2024-03-23 123839](https://github.com/bitfocus/companion-module-birddog-ptz/assets/164629973/aa17c675-c903-4de3-9466-8f86037e0da7)

![Schermafbeelding 2024-03-23 123900](https://github.com/bitfocus/companion-module-birddog-ptz/assets/164629973/7e530665-85ef-4c6e-8e2e-35a1d02dcc6b)

I have totally no knowledge about HEX-commands, nor about coding. Maybe this is not possible at all, because it's a NDI-command instead of Visca? So unfortunately I cannot do much more than address this feature. 

If someone likes to pick it up, i will be delighted to help with testing etc.

**Comment by bryce-seifert** [comment]
Thanks for the request! I've seen a few others ask about this on Facebook. I agree this would be useful, but there are two factors preventing it from being developed currently:

1. There is no documented API for controlling these features on the [BirdDog API site](https://birddog.tv/AV/API/index.html)
2. It's also a question of, if there was an API, whether the commands would need to go to the PTZ camera directly or to Camera Control. I'd guess Camera Control, and that would likely need to be a different module to avoid confusion since not everyone who uses the PTZ will use Camera Control in tandem.


I'm going to close this for now since it doesn't seem possible currently, but if BirdDog does introduce an API for Cam Control, I can take a look at developing against that.
