### ISSUE TITLE
only lower presets working on P200 latest stable firmware

### ISSUE THREAD

**Issue by schwtyl** [bitfocus/companion-module-birddog-ptz#60]
I'm using the latest stable P200 firmware, and have tried the latest stable & beta builds of companion, and only the lower presets are working, though my application uses 11-19 and "Recall Preset" does not work for these.

I saw that there was another closed Issue related to this, but it said it was resolved.  Perhaps they meant only for the latest BirdDog 5.0 firmware?  However, that is a beta firmware release, so I'd think this module would want to support the current/latest stable firmware too? It seems this module could detect that the P200 firmware isn't 5.0 so fallback on the old way of doing presets?

Companion Version: 2.2.2 and 2.3.0+4510-beta-b1f7c512
P200 firmware: BirdDog P200 A4_A5 4.5.3418-LTS

{"FirmwareVersion":"BirdDog P200 A4_A5 4.5.3418-LTS","Format":"CAM 1","HostName":"birddog2","IPAddress":"192.168.0.12","NetworkConfigMethod":"static","NetworkMask":"255.255.255.0","SerialNumber":"801f12f762ef","Status":"active"}

**Comment by jmcc94** [comment]
@schwtyl - Unfortunately using the v4 FW, the API only allows presets 1-9 to be saved & recalled. This is fixed in v5

The module was rewritten to use the API, rather than the old way of using VISCA commands.

Due to the future being the API, I'm not sure if we will look to add VISCA control of presets back into the module....will have a think
