### ISSUE TITLE
Connection but no press action

### ISSUE THREAD

**Issue by BW-TH** [bitfocus/companion-module-birddog-ptz#67]
i have a connection to birddog, but when i use it for an press action the bird dog connection is not liste
![connection](https://user-images.githubusercontent.com/88616334/181459804-0e7b0f22-3cde-47ea-8ea9-d2a25ac6e02c.png)
![action](https://user-images.githubusercontent.com/88616334/181459813-b4bb5381-436f-4597-acda-3b04c65c133a.png)
d

**Comment by jmcc94** [comment]
@BW-TH. There's been an issue with detecting the model of the camera with the newer models or some models running the latest FW.

This has been partly fixed in the latest beta of the model, which will be in the latest beta of Companion. 

What model is it, running what firmware, and what version of Companion?

**Comment by BW-TH** [comment]
Companion V 2.2.3 running on Raspberry and on Windows 11
Birddog P4K: 4.5.212-LTS

know i have imported an old version of configuration, and there the birddog button work, but is not editable

**Comment by jmcc94** [comment]
@BW-TH There is a new version of the module in the latest beta of companion that has improved detection of both camera & FW.
